site:
  title: Antora Site
  url: https://p4ali.github.io/antora
  start_page: 0.0.1@mesh:ROOT:network.adoc
  #start_page: 0.0.1@numpy:ROOT:environment.adoc
  #start_page: 0.0.1@ansible:ROOT:fundamental.adoc
content:
  sources:
  - url: ../../hands_on_ansible
  #- url: https://github.com/p4ali/hands_on_ansible.git
    branches: [master]
    start_path: docs
  - url: ../../python/numpy
    branches: [master]
    start_path: docs
  - url: ../../rust/rust_lang
    branches: [master]
    start_path: docs
  - url: ../mesh
    branches: [master]
  - url: ../antora_doc
    branches: [master]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  clean: true
  dir: ./docs
